### ISSUE TITLE
Dont validate email regex

### ISSUE THREAD

**Issue by matheusgr** [Klynger/my-blog#20]
https://github.com/Klynger/my-blog/blob/41a75c782987cff99b93e5ee03084a5ec3655eab/src/main/java/com/klynger/blog/models/User.java#L33

email validation using regex is a hard thing to do (see http://emailregex.com/). one easy way to validate an email is... send the email to whatever the user has set as input.

**Comment by Klynger** [comment]
Should I implement this solution for the project now, or just remove the regex? Because I was thinking of how I would do it to send the email back to the user, so I searched the internet and find that you have to put credentials of an email into the application.properties file (including password). If I do that it will be more complicated to run the project in some other computers due that you gonna have to set these variables. But I'm ok implementing this if need be, it seems pretty straightforward.

**Comment by matheusgr** [comment]
keep it as is :) it is just a heads up to you.
